services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: cricbuzz-backend

    ports:
      - "9090:9090"

    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_PASSWORD: ${DB_PASSWORD}
      CRICKET_API_KEY: ${CRICKET_API_KEY}

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    restart: unless-stopped


  postgres:
    image: postgres:16-alpine

    container_name: cricbuzz-postgres

    environment:
      POSTGRES_DB: cricbuzz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cricbuzz"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped


  redis:
    image: redis:7-alpine

    container_name: cricbuzz-redis

    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped


volumes:
  postgres_data:
  redis_data: