spring.application.name=cricbuzz-backend

server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

spring.datasource.username=postgres
spring.datasource.password=yash8252
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.open-in-view=true




cricket.api.base-url=https://api.cricapi.com/v1
cricket.api.key=3ee186eb-3d33-4e73-b955-a5f89f409a85